[custom]
;subconverter外部配置（Cloud）
;参考：https://github.com/tindy2013/subconverter/blob/master/base/config/example_external_config.ini

;自定义策略组
custom_proxy_group=🚀 外网代理`select`[]🌟 绝对可用`[]DIRECT
custom_proxy_group=🌐 直连规则`select`[]DIRECT`[]🚀 外网代理

custom_proxy_group=🚩 手动指定`select`[]♻️ 自动选择`.*
custom_proxy_group=♻️ 自动选择`url-test`.*`http://www.gstatic.com/generate_204`6,,10
custom_proxy_group=🌟 绝对可用`fallback`[]🚩 手动指定`[]♻️ 自动选择`http://www.gstatic.com/generate_204`10

;自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
ruleset=🌐 直连规则,clash-classic:https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/cn.yaml
ruleset=🚀 外网代理,clash-classic:https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/global.yaml
ruleset=🌐 直连规则,[]GEOIP,CN
ruleset=🚀 外网代理,[]FINAL

;节点筛选
include_remarks=(香港|HK|((?i)Hong Kong)|🇭🇰|台湾|TW|((?i)Taiwan)|🇹🇼|美国|US|((?i)United States)|🇺🇲)
