[custom]
;subconverter外部配置（Terminal）
;参考：https://github.com/tindy2013/subconverter/blob/master/base/config/example_external_config.ini

;自定义策略组
custom_proxy_group=🚀 外网代理`select`[]🚩 香港选择`[]🍌 台湾选择`[]🦁 狮城选择`[]👺 日本选择`[]🗽 美国选择`[]DIRECT
custom_proxy_group=📺 国外媒体`select`[]🚩 香港选择`[]🍌 台湾选择`[]🦁 狮城选择`[]👺 日本选择`[]🗽 美国选择`[]DIRECT
custom_proxy_group=🌐 直连规则`select`[]DIRECT`[]🚀 外网代理

custom_proxy_group=🚩 香港选择`select`[]♻️ 香港自动`(香港|HK|((?i)Hong Kong)|🇭🇰)
custom_proxy_group=🍌 台湾选择`select`[]♻️ 台湾自动`(台湾|TW|((?i)Taiwan)|🇹🇼)
custom_proxy_group=🦁 狮城选择`select`[]♻️ 狮城自动`(狮城|新加坡|SG|((?i)Singapore)|🇸🇬)
custom_proxy_group=👺 日本选择`select`[]♻️ 日本自动`(日本|JP|((?i)Japan)|🇯🇵)
custom_proxy_group=🗽 美国选择`select`[]♻️ 美国自动`(美国|US|((?i)United States)|🇺🇲)

custom_proxy_group=♻️ 香港自动`url-test`(香港|HK|((?i)Hong Kong)|🇭🇰)`http://www.gstatic.com/generate_204`5,,10
custom_proxy_group=♻️ 台湾自动`url-test`(台湾|TW|((?i)Taiwan)|🇹🇼)`http://www.gstatic.com/generate_204`5,,10
custom_proxy_group=♻️ 狮城自动`url-test`(狮城|新加坡|SG|((?i)Singapore)|🇸🇬)`http://www.gstatic.com/generate_204`5,,10
custom_proxy_group=♻️ 日本自动`url-test`(日本|JP|((?i)Japan)|🇯🇵)`http://www.gstatic.com/generate_204`5,,10
custom_proxy_group=♻️ 美国自动`url-test`(美国|US|((?i)United States)|🇺🇲)`http://www.gstatic.com/generate_204`5,,10

;自定义规则集
enable_rule_generator=true
overwrite_original_rules=true
ruleset=🌐 直连规则,clash-classic:https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/cn.yaml
ruleset=📺 国外媒体,clash-classic:https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/global-media.yaml
ruleset=🚀 外网代理,clash-classic:https://raw.githubusercontent.com/RikudouPatrickstar/Files/master/rules/rule-sets/global.yaml
ruleset=🌐 直连规则,[]GEOIP,CN
ruleset=🚀 外网代理,[]FINAL

;节点筛选
include_remarks=(香港|HK|((?i)Hong Kong)|🇭🇰|台湾|TW|((?i)Taiwan)|🇹🇼|狮城|新加坡|SG|((?i)Singapore)|🇸🇬|日本|JP|((?i)Japan)|🇯🇵|美国|US|((?i)United States)|🇺🇲)
